name: Daily Check-In

on:
  schedule:
    - cron: "16 0 * * *" # UTC 时间每天凌晨 0 点触发

jobs:
  check-in-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Download the latest check-in script
        run: |
          curl -o checkIn_Quark.py -L https://raw.githubusercontent.com/BNDou/Auto_Check_In/main/checkIn_Quark.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # 假设脚本需要 requests 库

      - name: Run the check-in script
        run: |
          python checkIn_Quark.py
        env:
          # 设置环境变量，用于脚本中可能需要的密钥或其他配置
          QUARK_COOKIE: ${{ secrets.QUARK_COOKIE }}
          # 添加其他可能需要的环境变量
